import { ListItem, OrderedList } from "@chakra-ui/react";
import Head from "next/head";
import Link from "next/link";
import DefaultContainer from "../../components/common/DefaultContainer";
import RoundedBox from "../../components/common/RoundedBox";
import TitleHeading from "../../components/common/TitleHeading";

const exerciceTypes = [
  {
    path: "/scenarios",
    description:
      "Transforming natural language phrases into propositional formulas",
  },
  {
    path: "/exercises/PL2",
    description: "Creating truth-tables from a propositional formula",
  },
  {
    path: "/exercises/PL3",
    description: "Converting formulas to a requested normal form",
  },
  /* {
    path: "/exercises/PL4",
    description: "Verify if a given formula is satisfiable or not",
  }, */
];

const Exercises = () => {
  return (
    <div>
      <Head>
        <title>Select Exercise</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DefaultContainer>
        <TitleHeading title="Classical Propositional Logic" />

        <RoundedBox>
          <OrderedList spacing={2} fontSize="lg">
            {exerciceTypes.map((exercise, index) => {
              return (
                <ListItem key={index}>
                  <Link href={exercise.path}>
                    <a>{exercise.description}</a>
                  </Link>
                </ListItem>
              );
            })}
          </OrderedList>
        </RoundedBox>
      </DefaultContainer>
    </div>
  );
};

export default Exercises;
