import Head from "next/head";
import ScenarioListWithProps from "../../components/ScenarioListWithProps";
import { Scenario } from "../../types";
import NoScenariosAvailable from "../../components/templates/NoScenariosAvailable";
import { getPublicData } from "../../utils/NetworkUtils";
import DefaultContainer from "../../components/common/DefaultContainer";
import TitleHeading from "../../components/common/TitleHeading";
import RoundedBox from "../../components/common/RoundedBox";

interface PageProps {
  scenarios: Scenario[];
}

const ScenariosPage = ({ scenarios }: PageProps) => {
  return (
    <>
      <Head>
        <title>Choose a scenario</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DefaultContainer>
        <TitleHeading title="Choose a scenario:" />

        {scenarios && scenarios.length > 0 ? (
          <RoundedBox>
            <ScenarioListWithProps data={scenarios}></ScenarioListWithProps>
          </RoundedBox>
        ) : (
          <NoScenariosAvailable />
        )}
      </DefaultContainer>
    </>
  );
};

export const getServerSideProps = async () => {
  const scenarios: Scenario[] = await getPublicData<Scenario[]>(
    "/api/scenarios/"
  );
  return {
    props: {
      scenarios: scenarios,
    },
  };
};

export default ScenariosPage;
