import Head from "next/head";
import { Center, Text } from "@chakra-ui/react";
import DefaultContainer from "../components/common/DefaultContainer";
import Formula from "../components/common/Formula";

const HomePage = () => {
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DefaultContainer>
        <Center h={"50vh"}>
          <Text fontSize="50px">Welcome to the Home page!</Text>
        </Center>
      </DefaultContainer>
    </>
  );
};

export default HomePage;
